name: GitHub Actions BobApp Back
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: 
  push:
    branches:
      - main
      - develop
      - feature/github-actions
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    name: Test back app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2   

      - name: Install dependencies
        run: mvn clean install
        working-directory: ./back       

      - name: Run tests with coverage
        run: mvn clean verify
        working-directory: ./back

      - name: Create test report
        uses: phoenix-actions/test-reporting@v8
        id: test-report
        if: success() || failure()
        with:
          name: Java Tests
          path: back/target/surefire-reports/*.xml
          reporter: java-junit     

      - name: Create coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./back/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true

  build:
    name: Build back app
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Build Frontend
        run: ...
        working-directory: ./back   
